steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Run tests
#- name: node
#  entrypoint: npm
#  args: ['test']
# Run custom commands
#- name: node
#  entrypoint: npm
#  args: ['run', 'build']
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/jeetar-v2:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/jeetar-v2:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/jeetar-v2:latest', '.']
  id: 'build-cloud-build-yaml'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/jeetar-v2:$BUILD_ID']
  waitFor: ['build-cloud-build-yaml']
  id: 'push-image-to-container-registry'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - ''
  - '--image'
  - 'gcr.io/$PROJECT_ID/jeetar-v2:$BUILD_ID'
  - '--region'
  - 'europe-west2'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
  id: 'deploy-to-cloud-run'
images:
- 'gcr.io/$PROJECT_ID/jeetar-v2:$BUILD_ID'
- 'gcr.io/$PROJECT_ID/jeetar-v2:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/jeetar-v2:latest'
